# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'dotenv'

package_json_content = File.read('../package.json')
package_json = JSON.parse(package_json_content)
version = package_json['version']

default_platform(:ios)

owner_name = "STS-ReactNative" # Update this value if you are not work on Saigon Technology Solutions

teamId = ENV["APPLE_TEAM_ID"]
envs = ['development', 'staging', 'production']
env = ''

platform :ios do
  before_all do |lane, options|
    env = assert_environment(**options)
  end

  desc "Build and upload to TestFlight"
  lane :upload do |options|
    appName = ENV["APP_NAME"]
    # my app name is HMezher Healthcare Demo
    # so i need to change the app name to HMezherHealthcareDemo
    appName = appName.gsub(" ", "")
    workspace ="./ios/#{appName}.xcworkspace"
    xcodeproj = "./ios/#{appName}.xcodeproj"
    increment_version_number(xcodeproj: xcodeproj, version_number: version)

    if options[:ci]
      build_number = increment_build_number(xcodeproj: xcodeproj, build_number: options[:buildNumber])

      cert
      sigh(
        force: true,
        app_identifier: ENV["APP_ID"],
        team_id: teamId,
      )

      update_code_signing_settings(
        use_automatic_signing: false,
        team_id: teamId,
        bundle_identifier: ENV["APP_ID"],
        profile_name: ENV["APP_ID"] + " AppStore",
        targets: [appName],
        code_sign_identity: 'Apple Distribution',
        path: xcodeproj
      )

      unlock_keychain(
        password: ENV["KEYCHAIN_PASSWORD"]
      )
    end

    build_app(
      workspace: workspace,
      scheme: appName,
      clean: true,
      xcargs: "-allowProvisioningUpdates",
      export_method: "app-store",
      export_options: {
        uploadBitcode: false,
        compileBitcode: false,
      }
    )

    # Upload to TestFlight
    UI.message("Uploading to TestFlight...")
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      app_identifier: ENV["APP_ID"],
      changelog: options[:changelog],
      itc_provider: teamId
    )
  end

  desc "Build iOS app"
  lane :build do |options|
    upload(env: options[:env], buildNumber: options[:buildNumber], ci: options[:ci], changelog: options[:changelog])
  end
end



platform :android do
  before_all do |lane, options|
    env = assert_environment(**options)
  end

  desc "Build file apk and upload to firebase app distribution"

  lane :upload do |options|
    # Run EAS Build locally
    if env === 'production'
      build_type = "AAB"
      task = "bundle"
    else
      build_type = "APK"
      task = "assemble"
    end
    gradle(
      task: task,
      build_type: "Release",
      project_dir: "./android",
#       properties: {
#         "VERSION_NAME" => version,
#         "versionCode" => options[:buildNumber]
#       }
    )
    if env === 'production'
      output_path = lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    else
      output_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    end
    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        release_notes: options[:changelog],
        groups: ENV["DISTRIBUTE_GROUP"],
        android_artifact_type: build_type,
        android_artifact_path: output_path,
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
    )
  end

  desc "Build Android app"
  lane :build do |options|
    upload(env: options[:env], buildNumber: options[:buildNumber], changelog: options[:changelog])
  end
end

private_lane :assert_environment do |options|
  env = if options[:env] != nil
    options[:env].downcase
  elsif ENV.key?('APP_ENV')
    ENV['APP_ENV']
  else
    UI.user_error!('Whoops, missing environment: Use `fastlane --env VALUE` where VALUE can be: ' + envs.inspect)
    prompt_for_environment
  end
end
